INSERT INTO QuestionsTable(Question, CategoryID, AnswersID)
VALUES
	-- General Anxiety test
	('How frequent do you worry about things that might happen in the future?',1,1),
	('How frequent do you feel nervous or anxious in new or unfamiliar situations?',1,1),
	('How frequent do you feel overwhelmed by stress?',1,1),
	('How frequent do you experience physical symptoms of anxiety, such as sweating, trembling, or a racing heartbeat?',1,1),
	('How frequent do you have trouble concentrating or focusing due to anxiety?',1,1),
	('How frequent do you avoid activities or situations because they make you anxious?',1,1),
	('How frequent do you have negative thoughts or feelings that you can''t control?',1,1),
	('How frequent do you feel like you''re in danger, even when there''s no immediate threat?',1,1),
	('How frequent do you have trouble falling or staying asleep due to anxiety?',1,1),
	('How frequent do you feel like you''re not in control of your thoughts or feelings?',1,1),
	('How frequent do you ever experienced a panic attack?',1,1),
	('How frequent do you find it hard to relax or unwind?',1,1),
	('Do you avoid watching or reading the news because it makes you anxious?',1,5),
	('How frequent do you struggle with social anxiety, such as feeling nervous or uncomfortable in group settings?',1,1),
	('How frequent do you ever sought professional help for anxiety?',1,1),
	('How frequent do you find yourself ruminating on past events or mistakes?',1,1),
	('Do you experience anxiety in certain specific situations, such as public speaking or flying on airplanes?',1,5),
	('How frequent do you experience physical symptoms of anxiety, such as nausea or headaches?',1,1),
	('Do you feel like anxiety affects your relationships or daily functioning?',1,5),
	('How frequent do you try relaxation techniques or other coping mechanisms to manage anxiety?',1,1),
	-- Alcohol Addiction Test
	('How frequent do you feel like you needed a drink in order to relax or feel better?',2,1),
    ('Have you ever tried to quit drinking, but found it difficult or impossible to do so?',2,5),
    ('Have you ever experienced withdrawal symptoms when you tried to stop drinking, such as shaking, sweating, or nausea?',2,5),
    ('Do you often drink more than you intended to, or for a longer period of time than you intended to?',2,5),
    ('Have you ever experienced blackouts or memory loss due to drinking?',2,5),
    ('Have you ever hidden your drinking from friends or loved ones?',2,5),
    ('Have you ever missed work, school, or other important obligations because of your drinking?',2,5),
    ('How frequent do you experience legal or financial problems due to your drinking habits?',2,1),
    ('Do you feel like you need to drink more in order to achieve some satisfaction?',2,5),
    ('Have you ever felt guilty or ashamed about your drinking habits?',2,5),
    ('Have you ever continued to drink even though it was causing problems in your life, such as relationship issues or health problems?',2,5),
    ('Do you feel irritable or restless when you''re not able to drink?',2,5),
    ('Have you ever experienced physical symptoms of alcohol dependence, such as tremors or sweating?',2,5),
    ('Do you often drink alone?',2,5),
    ('Do you frequently drink to the point of losing consciousness or passing out?',2,5),
    ('I experience memory problems or blackouts after drinking?',2,4),
    ('How frequent do you feel like you''re not able to have fun or socialize without drinking?',2,1),
    ('Have you ever lied or made excuses about your drinking habits?',2,5),
    ('How frequent do you experience physical health problems as a result of your drinking, such as liver disease or high blood pressure?',2,1),
    ('How frequent do you receive feedback from others that your drinking is causing them concern or harm?',2,1),
	-- Drug Addiction Test
    ('Have you ever felt like you needed drugs in order to feel normal or function in your daily life?',3,5),
    ('Have you ever tried to quit using drugs, but found it difficult or impossible to do so?',3,5),
    ('Have you ever experienced withdrawal symptoms when you tried to stop using drugs, such as nausea, vomiting, or anxiety?',3,5),
    ('Do you often use drugs in larger quantities or for a longer period of time than you intended to?',3,5),
    ('Have you ever experienced legal or financial problems due to your drug use?',3,5),
    ('Have you ever hidden your drug use from friends or loved ones?',3,5),
    ('How frequent do you miss work, school, or other important obligations because of your drug use?',3,5),
    ('Have you ever stolen or engaged in other illegal activities to obtain drugs?',3,5),
    ('How frequent do you experience cravings or strong urges to use drugs?',3,1),
    ('Have you ever experienced relationship problems due to your drug use?',3,5),
    ('Have you ever continued to use drugs even though it was causing problems in your life, such as relationship issues or health problems?',3,5),
    ('Do you feel like you''re not able to function without drugs, or that your drug use is necessary to get through the day?',3,5),
    ('Have you ever experienced physical symptoms of drug dependence, such as sweating, shaking, or seizures?',3,5),
    ('Do you often use drugs alone, or use more drugs when you''re alone?',3,5),
    ('Have you ever experienced blackouts or memory loss due to drug use?',3,5),
    ('Have you ever lied or made excuses about your drug use?',3,5),
    ('Do you feel like you''re not able to have fun or socialize without drugs?',3,5),
    ('Have you ever experienced physical health problems as a result of your drug use, such as liver disease or HIV/AIDS?',3,5),
    ('Have you ever received feedback from others that your drug use is causing them concern or harm?',3,5),
    ('Have you ever tried to cut back or quit using drugs, but found yourself unable to do so?',3,5),
	-- Shopping Addiction Test
	('How frequent do you spend more money shopping than you can afford?',4,1),
    ('Do you feel an adrenaline rush or a sense of excitement when you go shopping?',4,5),
    ('Do you have difficulty controlling your urge to shop, even when it''s not necessary?',4,5),
    ('How frequent do you buy things that you don''t need?',4,1),
    ('How frequent do you shop as a way to relieve stress or negative emotions?',4,1),
    ('Have you ever hidden purchases from loved ones or lied about how much you spent?',4,5),
    ('Do you experience feelings of guilt or regret after a shopping spree?',4,5),
    ('Have you ever experienced financial problems due to your shopping habits?',4,5),
    ('Do you feel like you''ve lost control over your shopping habits?',4,5),
    ('How frequent do you think about shopping, even when you''re not able to do it?',4,1),
    ('Have you ever missed a social or work obligation because you were shopping?',4,5),
    ('Do you often shop alone, and feel uncomfortable or irritable when you have to shop with others?',4,5),
    ('Do you have a strong emotional attachment to certain brands or stores?',4,5),
    ('Do you experience feelings of excitement or euphoria when you make a purchase?',4,5),
    ('Have you ever experienced relationship problems due to your shopping habits?',4,5),
    ('How frequent do you experience stress or anxiety when you''re not able to go shopping?',4,1),
    ('Do you find yourself buying items that you''ve already purchased in the past, or that are similar to items you already own?',4,5),
    ('How frequent do you purchase items with the intention of returning them later, but never actually follow through?',4,1),
    ('Do you feel like you need to shop in order to feel happy or fulfilled?',4,5),
    ('Have you ever tried to quit or reduce your shopping habits, but found it difficult or impossible to do so?',4,5),
	-- Gambling Addiction Test
	('To what extent do you engage in gambling activities?',5,1),
	('How frequently do you visit brick-and-mortar casinos?',5,1),
	('How often do you partake in lottery games or purchase scratch-off tickets?',5,1),
	('How frequently do you place bets on sports events through online platforms?',5,1),
	('How often do you participate in poker games, either with friends or in professional settings?',5,1),
	('To what degree do you play slot machines or other electronic gambling games?',5,1),
	('How frequently do you wager on horse racing or other forms of animal racing?',5,1),
	('How often do you play online casino games, such as blackjack, roulette, or slots?',5,1),
	('To what extent do you participate in high-stakes gambling?',5,1),
	('How frequently do you engage in social gambling activities, like playing cards with friends for money?',5,1),
	('How often do you engage in sports betting on professional or college sports?',5,1),
	('To what extent do you participate in online poker tournaments?',5,1),
	('How frequently do you play bingo or other social gambling games?',5,1),
	('How often do you buy raffle tickets for charity events or fundraisers?',5,1),
	('How frequently do you visit online gambling platforms for virtual casino games?',5,1),
	('To what extent do you bet on Esports competitions?',5,1),
	('How often do you participate in fantasy sports leagues for money?',5,1),
	('How frequently do you play skill-based gambling games, such as poker or blackjack?',5,1),
	('How often do you place bets on political events or outcomes?',5,1),
	('To what extent do you engage in online gambling through mobile apps?',5,1)
;
INSERT INTO QuestionCategory(Category)
VALUES
	('General Anxiety Test'),
	('Alcohol Addiction Test'),
	('Drug Addiction Test'),
    ('Shopping Addiction Test'),
    ('Gambling Addiction Test')
;
INSERT INTO AnswersTable(AnswerType,AnswerValues)
VALUES
	('5 Part Frequency Range', '{"0":"Never","1":"Not Frequent","2":"Sometimes","3":"Frequent","4":"Very Frequent"}'),
    ('5 Part Agreement Range', '{"0":"Strongly Disagree","1":"Disagree","2":"Neutral","3":"Agree","4":"Strongly Agree"}'),
    ('5 Part Probability Range', '{"0":"Never","1":"Unlikely","2":"50/50","3":"Likely","4":"Most Likely"}'),
    ('3 Part Agreement Range', '{"0":"Disagree","2":"Neutral","4":"Agree"}'),
	('Yes and No', '{"0":"No","4":"Yes"}');
INSERT INTO AdvicesTable(advice,details,CategoryID)
VALUES
    ('Prioritize Self-Care','Nurturing your physical and mental well-being is crucial for managing anxiety effectively. Establish a self-care routine that includes activities you enjoy and helps you relax.',1),
    ('Practice Deep Breathing','Deep breathing exercises can help calm your nervous system and reduce anxiety symptoms. Take slow, deep breaths, hold for a few seconds, and exhale gently.',1),
    ('Challenge Negative Thoughts','Recognize and challenge negative thoughts that fuel anxiety. Replace them with positive, rational, and realistic alternatives.',1),
    ('Establish a Support System','Surround yourself with understanding and supportive individuals who can provide encouragement and lend a listening ear during difficult times.',1),
    ('Engage in Regular Exercise','Physical activity releases endorphins, which boost your mood and reduce anxiety. Find an exercise routine that suits your preferences and engage in it regularly.',1),
    ('Limit Caffeine and Alcohol','Stimulants like caffeine and alcohol can exacerbate anxiety symptoms. Reduce your consumption of these substances or consider avoiding them altogether.',1),
    ('Practice Mindfulness','Mindfulness techniques, such as meditation or yoga, can help you stay present and manage anxiety. Focus on the present moment, observe your thoughts and feelings without judgment, and cultivate a sense of calm.',1),
    ('Establish a Sleep Routine','Consistent and quality sleep is essential for managing anxiety. Create a soothing bedtime routine, avoid electronic devices before bed, and ensure your sleep environment is comfortable and conducive to rest.',1),
    ('Break Tasks into Manageable Steps','Overwhelming tasks can contribute to anxiety. Break them down into smaller, achievable steps, and tackle them one at a time to reduce stress and anxiety.',1),
    ('Seek Professional Help','If anxiety significantly impacts your daily life, consider seeking professional help. Therapists and counselors can provide valuable guidance and support tailored to your specific needs.',1),
    ('Limit News and Social Media Exposure','Constant exposure to distressing news or social media can heighten anxiety. Set boundaries and allocate specific times for consuming such content to protect your mental well-being.',1),
    ('Engage in Relaxation Techniques','Experiment with relaxation techniques like progressive muscle relaxation, guided imagery, or aromatherapy. Find what works for you to promote relaxation and alleviate anxiety.',1),
    ('Maintain a Balanced Lifestyle','Strive for balance in all areas of your life, including work, relationships, and leisure. Setting realistic expectations and establishing healthy boundaries can help minimize anxiety triggers.',1),
    ('Practice Gratitude','Cultivating a grateful mindset can shift your focus from anxiety to the positive aspects of your life. Regularly express gratitude for the things, people, and experiences that bring you joy and contentment.',1),
    ('Be Kind to Yourself','Remember that anxiety is a common human experience, and it doesn''t define your worth. Practice self-compassion and treat yourself with kindness and understanding as you navigate your anxiety journey.',1),
    ('Acknowledge the Problem','Recognize and accept that you have an addiction. Honesty with yourself is the first step toward recovery.',2),
    ('Seek Professional Help','Consult with a healthcare professional or addiction specialist who can provide guidance, support, and personalized treatment options tailored to your specific needs.',2),
    ('Build a Support Network','Surround yourself with supportive individuals who understand your struggle and can offer encouragement and accountability throughout your recovery journey.',2),
    ('Set Clear Goals','Establish realistic and achievable goals for your recovery. Breaking them down into smaller milestones can help you stay motivated and focused.',2),
    ('Avoid Triggers','Identify and avoid people, places, or situations that trigger cravings or temptations to engage in addictive behaviors. This may involve making changes to your social circle or daily routines.',2),
    ('Develop Healthy Coping Mechanisms','Discover and practice healthy coping mechanisms to replace addictive behaviors. This could include exercise, meditation, creative outlets, or engaging in hobbies that bring you joy.',2),
    ('Create a Structured Routine','Establishing a daily routine can provide stability and reduce the likelihood of relapse. Plan your day with productive and fulfilling activities that keep you focused on your recovery goals.',2),
    ('Practice Self-Care','Prioritize self-care to nurture your physical, mental, and emotional well-being. Engage in activities that promote relaxation, reduce stress, and contribute to your overall health.',2),
    ('Educate Yourself','Learn about your addiction and its effects to gain a better understanding of its impact on your life. Knowledge empowers you to make informed decisions and helps you navigate challenges.',2),
    ('Practice Mindfulness','Stay present and cultivate mindfulness in your daily life. This can help you become more aware of your triggers, cravings, and emotions, enabling you to respond to them in healthier ways.',2),
    ('Engage in Therapy or Counseling','Consider individual or group therapy to address underlying issues that may have contributed to your addiction. Therapy can provide valuable insights and tools for long-term recovery.',2),
    ('Create a Relapse Prevention Plan','Work with professionals to develop a relapse prevention plan that includes strategies for identifying warning signs, managing cravings, and seeking help when needed.',2),
    ('Practice Gratitude and Positivity','Focus on the positive aspects of your life and cultivate a sense of gratitude. This mindset shift can help you maintain motivation, resilience, and a positive outlook on your recovery journey.',2),
    ('Take One Day at a Time','Recovery is a process that requires patience and perseverance. Focus on the present moment and celebrate each small victory along the way.',2),
    ('Be Kind to Yourself','Recovery is not always linear, and setbacks may occur. Practice self-compassion and forgive yourself if you stumble. Remember that seeking help and working toward recovery is a courageous and worthy endeavor.',2)
;
INSERT INTO WebLinksTable(Website,URL,Details,CategoryID)
VALUES
    ('BetterHelp','https://www.betterhelp.com/get-started/','Therapy On Your Schedule. Text, Phone & Online Therapy With a Local Licensed Therapist. Therapist Available Now. ',1),
    ('MindSpot Clinic','https://mindspot.org.au/','Free online and telephone treatment for anxiety disorders and depression. Provides research based courses through the E-Centre Clinic at Macquarie University. Courses begin every two weeks.',1),
    ('eCentreClinic','https://www.ecentreclinic.org/','An internet based research clinic that provides free online treatment courses for people with symptoms of worry, anxiety, stress, depression, low moods and chronic pain.',1),
    ('This Way Up','https://thiswayup.org.au/','This Way Up is an internet-based treatment program for anxiety and depression. These courses are designed to help people experiencing symptoms of anxiety and or depression for a small fee. Each course consists of six structured sessions.',1),
    ('MoodGym','https://moodgym.com.au/','Provides a free online cognitive behavioral therapy program for people experiencing depression.',1),
    ('ecouch','https://ecouch.com.au/info/new_ecouch','ecouch is an online service that helps people experiencing emotional problems, including anxiety and depression.',1),
    ('Fear Drop','http://www.feardrop.com/','Graded exposure online program for people with a specific phobia (fear) disorder.',1),
    ('Centre for Mental Health','https://www.mq.edu.au/research/research-centres-groups-and-facilities/healthy-people/centres/centre-for-emotional-health-ceh','Conducts research, training and treatment of Anxiety Disorders, both for children and adults. It is a Macquarie University centre for research excellence.',1),
    ('The Clinical Research Unit for Anxiety and Depression (CRUfAD)','https://crufad.org/','This is a joint research facility between UNSW and St. Vincent Hospital in Sydney. CRUfAD has been classified as World Health Organisation (WHO) Collaborative Centre in e-health',1),
    ('Mental Health Online','https://www.mentalhealthonline.org.au/','An Internet Based treatment clinic for people with mental health problems. It is an initiative of the National E-Therapy Centre at the Swinburne University of Technology and it is funded by the Federal Government. It provides Information, Clinical Assessments and Free Online treatment programs.',1),
    ('Beyond Blue','https://www.beyondblue.org.au/','A national-wide organization, working towards an increased awareness and understanding of Anxiety and Depression.  Provides resources for consumers and carers, an information line, web-chat, online forums, a directory for GPs trained in mental health and more.',1),
    ('The Black Dog Institute','https://www.blackdoginstitute.org.au/','A non-for-profit organization and a world leader in research, diagnosis, treatment and prevention of depression and bipolar disorder.',1),
    ('Bluepages','https://bluepages.anu.edu.au/','This website provides information on depression and treatments that are available. Also provides online support for people experiencing depression.',1),
    ('e-headspace','https://headspace.org.au/online-and-phone-support/','Website which provides free online and telephone support & counselling for young people between the ages of 12-25.',1),
    ('Lifeline One-to-One Crisis Support Chat','https://www.lifeline.org.au/','Provides online support for people in crisis. Online chat available 8pm-12am 7 days a week. Call Lifeline on 13 11 14 after these hours.',1),
    ('Mens Line','https://mensline.org.','Provides professional online and telephone support, and information service to Australian men 24/7',1),
    ('Your Room','https://yourroom.health.nsw.gov.au/Pages/home.aspx','Drug and alcohol information website. Information on where to get help, support and treatment options all through NSW. Joint initiative of NSW Health and St Vincent''s Alcohol and Drug Information Service',1),
    ('Shed Online','https://mensshed.org/the-shed-online/','A website which provides an online social community for men. Provides information on health and lifestyle topics, discussion forums, online chat, news and events in the community.',1),
    ('Open Arms','https://www.openarms.gov.au/','Website from the Department of Veteran''s Affairs to encourage veterans to maintain mental health, understand mental health and access mental health. Includes self help tools, fact sheets, treatment options and publications.',1),
    ('National Network of Adult and Adolescent Children who have a Mentally Ill Parent (NNAAMI)','http://www.nnaami.org/','NNAAMI informs the community and government of common needs and life experience of people with a parent of a mental illness, provides assistance, support, counselling and support groups.',1),
    ('Reach Out','https://au.reachout.com/','A youth mental health service, providing information on mental health, drug and alcohol, physical health, wellbeing, bullying and more.',1),
    ('Transcultural Mental Health Centre','https://www.dhi.health.nsw.gov.au/transcultural-mental-health-centre','TMHC is a NSW state wide non-for-profit organization that supports good mental health for people from culturally and linguistically diverse communities.',1),
    ('MyCompass','https://www.mycompass.org.au/','MyCompass is an interactive self-help service which aims to promote wellbeing and resilience. This website allows people to track their moods, write about them and view information and tips.',1),
    ('Mood Swings','https://moodswings.net.au/','Online self-help tools for people with bipolar disorder.',1),
    ('Centre for Clinical Interventions','https://www.cci.health.wa.gov.au/','The CCI site has online workbooks for various different types of anxiety as well as depression. The workbooks consist of a number of modules that you can complete online or print off so that you are able to work through them by hand. The service provides current evidence-supported practice. CCI provides free treatments for adults suffering from anxiety, affective and eating disorders; conducts research and provides training and supervision for mental health professionals in psychotherapy.',1),
    ('Treatment for Alcohol Problems: Finding and Getting Help','https://www.niaaa.nih.gov/publications/brochures-and-fact-sheets/treatment-alcohol-problems-finding-and-getting-help','This guide is written for individuals, and their family and friends, who are looking for options to address alcohol problems. It is intended as a resource to understand what treatment choices are available and what to consider when selecting among them.',2),
    ('Rethinking Drinking','https://www.rethinkingdrinking.niaaa.nih.gov/','This website contains background information about drinking patterns and the risk for alcohol use disorder.',2),
    ('Alcoholics Anonymous (AA)','https://www.aa.org/','Phone: 212-870-3400 (or check your local phone directory under "Alcoholism")',2),
    ('LifeRing','https://lifering.org/','Phone: 800-811-4142',2),
    ('Secular Organizations for Sobriety','https://www.sossobriety.org/','Phone: 323-666-4295',2),
    ('SMART Recovery','https://www.smartrecovery.org/','Phone: 440-951-5357',2),
    ('A-CHESS','https://www.chess.health/','A mobile relapse prevention tool; available from some specialty treatment providers and programs.',2),
    ('CBT4CBT','https://cbt4cbt.com/','A self-guided, web-based cognitive behavioral therapy program that teaches skills to help people stop or reduce drinking; health professionals can provide a prescription.',2),
    ('CheckUp & Choices','https://checkupandchoices.com/alcohol/?utm_source=NIH&utm_medium=referral&utm_content=helpful-links-cnc-name','A digital self-help program to guide people in deciding whether to change their drinking habits and developing skills to make a change.',2),
    ('Al-Anon','https://al-anon.org/','This mutual help group offers “strength and hope for friends and families of problem drinkers.”',2),
    ('HelpGuide.org','https://www.helpguide.org/articles/addictions/drug-abuse-and-addiction.htm','Do you or someone you love have a problem with substance abuse? Explore the warning signs and how to get the best help.',3),
    ('Get Smart About Drugs','https://www.getsmartaboutdrugs.gov/find-help',' Use this site to find substance abuse treatment centers specifically for teens in your area',3),
    ('DrugAbuse.com','https://drugabuse.com/','At DrugAbuse.com, we not only educate you on the facts and figures of drugs and their misuse, but we also guide you toward the drug treatment you need.',3),
    ('Cocaine Anonymous UK','https://www.cocaineanonymous.org.uk/','Help and support for anyone who wants to stop using cocaine.',3),
    ('Narcotics Anonymous','https://ukna.org/','Support for anyone who wants to stop using drugs.',3),
    ('We Are With You','https://www.wearewithyou.org.uk/','Supports people with drug, alcohol or mental health problems, and their friends and family.',3),
    ('Adfam','https://adfam.org.uk/','Information and support for friends and family of people with drug or alcohol problems.',3),
    ('DrugFAM','https://www.drugfam.co.uk/','Provides support to anyone affected by someone else''s harmful use of drugs, alcohol or gambling.',3),
    ('Talkspace Online Therapy Ratings & Reviews','https://www.mentalhelp.net/best-online-therapy/reviews/talkspace/?utm_source=psychguides&utm_medium=text_link&utm_campaign=article_resources','Licensed therapists and psychiatrists are available for virtual sessions via Talkspace. From virtual counseling to medication management services, Talkspace online therapy may be covered by your insurance provider.',4),
    ('ReGain Online Therapy Ratings & Reviews','https://www.mentalhelp.net/best-online-therapy/reviews/regain/?utm_source=psychguides&utm_medium=text_link&utm_campaign=article_resources',' Online couples counseling has never been easier, thanks to ReGain. Their licensed therapists specialize in helping couples improve communication skills to resolve conflict in healthy ways.',4),
    ('BetterHelp Online Therapy Ratings & Reviews','https://www.mentalhelp.net/best-online-therapy/reviews/betterhelp/?utm_source=psychguides&utm_medium=text_link&utm_campaign=article_resources','BetterHelp offers online therapy services from licensed professionals through an easy-to-use website and app. ',4),
    ('Finding Help for Shopping Addiction - Healthline','https://www.healthline.com/health/addiction/shopping','Compulsive buying disorder causes you to spend money, even if you do not have it, regardless of whether you need the product you''re buying. Treatment can include recovery classes.',4),
    ('Shopping Addiction Fueled By Online Shopping','https://www.addictioncenter.com/news/2020/01/shopping-addiction-online-shopping/','Get professional help from an online addiction and mental health counselor from BetterHelp.',4),
    ('Shopping addiction help','https://www.ukat.co.uk/addiction/behavioural/shopping/','The most effective way to recover from shopping addiction is by attending a professional addiction treatment centre. ',4),
    ('Shopping Addiction: Signs, Causes, and Coping','https://www.verywellmind.com/shopping-addiction-4157288',' Develop other coping strategies · Enlist the help of others · Limit access to credit and cash',4),
    ('everyday Health','https://www.everydayhealth.com/emotional-health/what-is-shopping-addiction/','What are the symptoms of shopping addiction? And where can you seek help? Here, experts weigh in on what you need to know.',4),
    ('Gamblers Anonymous','http://www.gamblersanonymous.org/ga/addresses','offers 12-step support meetings for people with a gambling problem,',5),
    ('Gam-Anon','https://www.gam-anon.org/','offers support for the problem gambler''s family members.',5),
    ('Freedom from Problem Gambling','http://www.uclagamblingprogram.org/treatment/wb/US_WB.pdf','Self-help workbook for compulsive gamblers, with tips on how to avoid relapse and fight gambling urges. (UCLA Gambling Studies Program)',5),
    ('Problem Gamblers and their Finances','http://www.ncpgambling.org/files/public/problem_gamblers_finances.pdf','Guide for treatment professionals on how to help a problem gambler cope with financial problems. (National Endowment for Financial Education)',5),
    ('Personal Financial Strategies for the Loved Ones of Problem Gamblers ','https://www.ncpgambling.org/wp-content/uploads/2014/08/loved_ones_guide_ncpg_booklet.pdf','How to deal with financial issues due to a loved one''s gambling. (National Council on Problem Gambling)',5),
    ('National Helpline 1-800-GAMBLER','https://www.ncpgambling.org/help-treatment/national-helpline-1-800-522-4700/','Help is available 24/7 and is 100% confidential. The National Problem Gambling Helpline Network also includes text and chat services.',5),
    ('GamCare','https://www.gamcare.org.uk/','offers free information, support and counselling for people who have problems with gambling in the UK.',5),
    ('Gamblers Anonymous','https://www.gamblersanonymous.org.uk/','Runs local support groups that use the same 12-step approach to recovery from addiction as Alcoholics Anonymous.',5),
    ('Gambling Addiction: Get Help Today','https://www.addictioncenter.com/drugs/gambling-addiction/','Gambling disorder treatment, 100% online. Discuss your treatment needs. Get matched to a counselor.',5),
    ('National Council on Problem Gambling','https://www.ncpgambling.org/','The National Council on Problem Gambling (NCPG) exists to support, advocate for, and provide resources for people who have problems gambling and their loved ones. ',5),
    ('Problem Gambling Guide','https://www.problemgamblingguide.com/','The Problem Gambling Guide details a step-by-step approach to identifying problem gambling, seeking treatment and beginning recovery, and maintaining a lifestyle free of addiction and relapse.',5)
;