INSERT INTO QuestionsTable(Question, CategoryID, AnswersID)
VALUES
	-- General Anxiety test
	('How frequent do you worry about things that might happen in the future?',1,1),
	('How frequent do you feel nervous or anxious in new or unfamiliar situations?',1,1),
	('How frequent do you feel overwhelmed by stress?',1,1),
	('How frequent do you experience physical symptoms of anxiety, such as sweating, trembling, or a racing heartbeat?',1,1),
	('How frequent do you have trouble concentrating or focusing due to anxiety?',1,1),
	('How frequent do you avoid activities or situations because they make you anxious?',1,1),
	('How frequent do you have negative thoughts or feelings that you can''t control?',1,1),
	('How frequent do you feel like you''re in danger, even when there''s no immediate threat?',1,1),
	('How frequent do you have trouble falling or staying asleep due to anxiety?',1,1),
	('How frequent do you feel like you''re not in control of your thoughts or feelings?',1,1),
	('How frequent do you ever experienced a panic attack?',1,1),
	('How frequent do you find it hard to relax or unwind?',1,1),
	('Do you avoid watching or reading the news because it makes you anxious?',1,5),
	('How frequent do you struggle with social anxiety, such as feeling nervous or uncomfortable in group settings?',1,1),
	('How frequent do you ever sought professional help for anxiety?',1,1),
	('How frequent do you find yourself ruminating on past events or mistakes?',1,1),
	('Do you experience anxiety in certain specific situations, such as public speaking or flying on airplanes?',1,5),
	('How frequent do you experience physical symptoms of anxiety, such as nausea or headaches?',1,1),
	('Do you feel like anxiety affects your relationships or daily functioning?',1,5),
	('How frequent do you try relaxation techniques or other coping mechanisms to manage anxiety?',1,1),
	-- Alcohol Addiction Test
	('How frequent do you feel like you needed a drink in order to relax or feel better?',2,1),
    ('Have you ever tried to quit drinking, but found it difficult or impossible to do so?',2,5),
    ('Have you ever experienced withdrawal symptoms when you tried to stop drinking, such as shaking, sweating, or nausea?',2,5),
    ('Do you often drink more than you intended to, or for a longer period of time than you intended to?',2,5),
    ('Have you ever experienced blackouts or memory loss due to drinking?',2,5),
    ('Have you ever hidden your drinking from friends or loved ones?',2,5),
    ('Have you ever missed work, school, or other important obligations because of your drinking?',2,5),
    ('How frequent do you experience legal or financial problems due to your drinking habits?',2,1),
    ('Do you feel like you need to drink more in order to achieve some satisfaction?',2,5),
    ('Have you ever felt guilty or ashamed about your drinking habits?',2,5),
    ('Have you ever continued to drink even though it was causing problems in your life, such as relationship issues or health problems?',2,5),
    ('Do you feel irritable or restless when you''re not able to drink?',2,5),
    ('Have you ever experienced physical symptoms of alcohol dependence, such as tremors or sweating?',2,5),
    ('Do you often drink alone?',2,5),
    ('Do you frequently drink to the point of losing consciousness or passing out?',2,5),
    ('I experience memory problems or blackouts after drinking?',2,4),
    ('How frequent do you feel like you''re not able to have fun or socialize without drinking?',2,1),
    ('Have you ever lied or made excuses about your drinking habits?',2,5),
    ('How frequent do you experience physical health problems as a result of your drinking, such as liver disease or high blood pressure?',2,1),
    ('How frequent do you receive feedback from others that your drinking is causing them concern or harm?',2,1),
	-- Drug Addiction Test
    ('Have you ever felt like you needed drugs in order to feel normal or function in your daily life?',3,5),
    ('Have you ever tried to quit using drugs, but found it difficult or impossible to do so?',3,5),
    ('Have you ever experienced withdrawal symptoms when you tried to stop using drugs, such as nausea, vomiting, or anxiety?',3,5),
    ('Do you often use drugs in larger quantities or for a longer period of time than you intended to?',3,5),
    ('Have you ever experienced legal or financial problems due to your drug use?',3,5),
    ('Have you ever hidden your drug use from friends or loved ones?',3,5),
    ('How frequent do you miss work, school, or other important obligations because of your drug use?',3,5),
    ('Have you ever stolen or engaged in other illegal activities to obtain drugs?',3,5),
    ('How frequent do you experience cravings or strong urges to use drugs?',3,1),
    ('Have you ever experienced relationship problems due to your drug use?',3,5),
    ('Have you ever continued to use drugs even though it was causing problems in your life, such as relationship issues or health problems?',3,5),
    ('Do you feel like you''re not able to function without drugs, or that your drug use is necessary to get through the day?',3,5),
    ('Have you ever experienced physical symptoms of drug dependence, such as sweating, shaking, or seizures?',3,5),
    ('Do you often use drugs alone, or use more drugs when you''re alone?',3,5),
    ('Have you ever experienced blackouts or memory loss due to drug use?',3,5),
    ('Have you ever lied or made excuses about your drug use?',3,5),
    ('Do you feel like you''re not able to have fun or socialize without drugs?',3,5),
    ('Have you ever experienced physical health problems as a result of your drug use, such as liver disease or HIV/AIDS?',3,5),
    ('Have you ever received feedback from others that your drug use is causing them concern or harm?',3,5),
    ('Have you ever tried to cut back or quit using drugs, but found yourself unable to do so?',3,5),
	-- Shopping Addiction Test
	('How frequent do you spend more money shopping than you can afford?',4,1),
    ('Do you feel an adrenaline rush or a sense of excitement when you go shopping?',4,5),
    ('Do you have difficulty controlling your urge to shop, even when it''s not necessary?',4,5),
    ('How frequent do you buy things that you don''t need?',4,1),
    ('How frequent do you shop as a way to relieve stress or negative emotions?',4,1),
    ('Have you ever hidden purchases from loved ones or lied about how much you spent?',4,5),
    ('Do you experience feelings of guilt or regret after a shopping spree?',4,5),
    ('Have you ever experienced financial problems due to your shopping habits?',4,5),
    ('Do you feel like you''ve lost control over your shopping habits?',4,5),
    ('How frequent do you think about shopping, even when you''re not able to do it?',4,1),
    ('Have you ever missed a social or work obligation because you were shopping?',4,5),
    ('Do you often shop alone, and feel uncomfortable or irritable when you have to shop with others?',4,5),
    ('Do you have a strong emotional attachment to certain brands or stores?',4,5),
    ('Do you experience feelings of excitement or euphoria when you make a purchase?',4,5),
    ('Have you ever experienced relationship problems due to your shopping habits?',4,5),
    ('How frequent do you experience stress or anxiety when you''re not able to go shopping?',4,1),
    ('Do you find yourself buying items that you''ve already purchased in the past, or that are similar to items you already own?',4,5),
    ('How frequent do you purchase items with the intention of returning them later, but never actually follow through?',4,1),
    ('Do you feel like you need to shop in order to feel happy or fulfilled?',4,5),
    ('Have you ever tried to quit or reduce your shopping habits, but found it difficult or impossible to do so?',4,5),
	-- Gambling Addiction Test
	('To what extent do you engage in gambling activities?',5,1),
	('How frequently do you visit brick-and-mortar casinos?',5,1),
	('How often do you partake in lottery games or purchase scratch-off tickets?',5,1),
	('How frequently do you place bets on sports events through online platforms?',5,1),
	('How often do you participate in poker games, either with friends or in professional settings?',5,1),
	('To what degree do you play slot machines or other electronic gambling games?',5,1),
	('How frequently do you wager on horse racing or other forms of animal racing?',5,1),
	('How often do you play online casino games, such as blackjack, roulette, or slots?',5,1),
	('To what extent do you participate in high-stakes gambling?',5,1),
	('How frequently do you engage in social gambling activities, like playing cards with friends for money?',5,1),
	('How often do you engage in sports betting on professional or college sports?',5,1),
	('To what extent do you participate in online poker tournaments?',5,1),
	('How frequently do you play bingo or other social gambling games?',5,1),
	('How often do you buy raffle tickets for charity events or fundraisers?',5,1),
	('How frequently do you visit online gambling platforms for virtual casino games?',5,1),
	('To what extent do you bet on Esports competitions?',5,1),
	('How often do you participate in fantasy sports leagues for money?',5,1),
	('How frequently do you play skill-based gambling games, such as poker or blackjack?',5,1),
	('How often do you place bets on political events or outcomes?',5,1),
	('To what extent do you engage in online gambling through mobile apps?',5,1)
;
